enum DailyLines {
    static let all: [String] = [
        "Morning. Again.",
        "Here we are.",
        "Another morning.",
        "Still here.",
        "Same place.",
        "A new number.",
        "Day by day.",
        "See what happens.",
        "Notice something.",
        "Look again.",
        "Not quite the same.",
        "Something shifted.",
        "A little different.",
        "Keep watching.",
        "Stay for today.",
        "Maybe this time.",
        "See it differently.",
        "Try once more.",
        "Learn something.",
        "Know this day.",
        "There is time.",
        "You have today.",
        "Start where you are.",
        "The day is open.",
        "Let today happen.",
        "See where it goes.",
        "One more morning.",
        "Today knows nothing yet.",
        "The day isn't written.",
        "Something can be different.",
        "See what today becomes.",
        "Tomorrow can wait.",
    ]
}
